### ISSUE TITLE
ReferenceError: streamName is not defined

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/node_smartystreets#29]
```
/home/vagrant/usr/lib/node_modules/smartystreets/program.js:110
  writeStream.pipe( fs.createWriteStream(options.output+'/'+streamName+'.csv')
                                                            ^
ReferenceError: streamName is not defined
    at Object.<anonymous> (/home/vagrant/usr/lib/node_modules/smartystreets/program.js:110:61)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by seamusabshere** [comment]
fixed in 5619aea98c394ea127d1030ad6c3de7475cd11c8
