### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/node_smartystreets#30]
```
$ node_modules/.bin/smartystreets -i /tmp/SELECT_private_data_id_private_data_house_number_and_str20150203-3878-shcbth -o /tmp/tmpSELECT_private_data_id_private_data_house_number_and_str20150203-3878-shcbth.geocode20150203-3878-1xn91uo --auth-id XXX --auth-token XXX --street-col house_number_and_street --zipcode-col postcode
1050 rows done, 94.57% geocoded, 2776 rows per second
2030 rows done, 94.68% geocoded, 3499 rows per second
3010 rows done, 94.52% geocoded, 3981 rows per second
4060 rows done, 94.90% geocoded, 4329 rows per second
5040 rows done, 94.76% geocoded, 4567 rows per second
6020 rows done, 94.47% geocoded, 4715 rows per second
7000 rows done, 94.23% geocoded, 4445 rows per second

Error: write after end
    at writeAfterEnd (/vagrant/rolodeck/node_modules/smartystreets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (/vagrant/rolodeck/node_modules/smartystreets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:192:5)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at DestroyableTransform.<anonymous> (_stream_readable.js:573:7)
    at DestroyableTransform.EventEmitter.emit (events.js:92:17)
    at onwriteDrain (/vagrant/rolodeck/node_modules/smartystreets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:300:12)
    at afterWrite (/vagrant/rolodeck/node_modules/smartystreets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:288:5)
    at onwrite (/vagrant/rolodeck/node_modules/smartystreets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:281:7)
    at WritableState.onwrite (/vagrant/rolodeck/node_modules/smartystreets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/vagrant/rolodeck/node_modules/smartystreets/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:5)
```

**Comment by tbryenton** [comment]
@devTristan note that I emailed you the relevant file.

This is `critical`.

**Comment by tbryenton** [comment]
**no longer critical**
