### ISSUE TITLE
barfs on malformed input rows

### ISSUE THREAD

**Issue by wboykinm** [faradayio/node_smartystreets#33]
For example, this type of data in a row:

`...|""|""|"HARRY W STANHOPE JEAN H "1 STANHOPE"|"HARRY"|"W STANHOPE JEAN H "1"|"STANHOPE"|...`

. . . will throw this and bail out of the whole process:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parse Error: expected: '"' got: '1'. at '1 STANHOPE""
    at parseEscapedItem (/home/ubuntu/node_modules/smartystreets/node_modules/fast-csv/lib/parser/parser.js:79:19)
    at ParserStream.parseLine [as parser] (/home/ubuntu/node_modules/smartystreets/node_modules/fast-csv/lib/parser/parser.js:174:30)
    at ParserStream._parseLine [as _parse] (/home/ubuntu/node_modules/smartystreets/node_modules/fast-csv/lib/parser/parser_stream.js:164:25)
    at ParserStream.extended.extend._transform (/home/ubuntu/node_modules/smartystreets/node_modules/fast-csv/lib/parser/parser_stream.js:198:18)
    at ParserStream.Transform._read (_stream_transform.js:179:10)
    at ParserStream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:223:10)
    at clearBuffer (_stream_writable.js:301:5)
    at onwrite (_stream_writable.js:259:7)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at afterTransform (_stream_transform.js:99:5)
```

This is a node `fast-csv` failure, related to a [parsing resumability problem they've opted not to fix](https://github.com/C2FO/fast-csv/issues/135).

**Comment by seamusabshere** [comment]
you gotta fix the csv before it ever gets to node_smartystreets
